### ISSUE TITLE
API 启动报错 401

### ISSUE THREAD

**Issue by RexWzh** [zhipuai/zhipuai-sdk-python#18]
我在尝试使用 OpenAI 风格的 API 接入智谱AI，但遇到了一些问题。使用 Python 包可以成功地访问智谱AI，然而，当我尝试集成到其他项目中时，遇到了鉴权失败的问题。

具体地，我尝试了以下 Python 代码：

```python
from llama_index.llms import OpenAI
chat = OpenAI(api_key=api_key, api_base="https://open.bigmodel.cn/api/paas/v4")
chat.complete("hello")
```

[ API 文档](https://open.bigmodel.cn/dev/api)提供了 Python 包的调用方法，没有给出 `curl` 的示例。尽管使用 `zhipuai` 能够正常访问，但不好做扩展迁移。

提问题前，我用 APIfox 做了调试，但仍存在 401 鉴权错误。以下是我尝试的 `curl` 命令：

```bash
curl --location --request POST 'https://open.bigmodel.cn/api/paas/v4/chat/completions' \
--header 'Authorization: Bearer <真实密钥>' \
--header 'Content-Type: application/json; charset=UTF-8' \
--header 'Accept: */*' \
--header 'Host: open.bigmodel.cn' \
--header 'Connection: keep-alive' \
--data-raw '{"model": "glm-3-turbo", "messages": [{"role": "system", "content": "say hi"}]}'
```

感谢读到这里！希望能提供更详细 API 示例的文档！或者能否兼容 OpenAI 的模式。

**Comment by yfflood** [comment]
我在运行langchain的官方示例（https://open.bigmodel.cn/dev/api#langchain_sdk ）的时候也401了
