### ISSUE TITLE
调用 ChatGLM-Pro API 接口进行多轮对话问题

### ISSUE THREAD

**Issue by zapp926** [zhipuai/zhipuai-sdk-python#4]
在对话开始前前面设置好 Prompt，进行几轮对话后，发现模型就开始重复我发的消息。

每次都能100%复现，具体表现如下图。请问怎么更改或者设置呢？谢谢。
<img width="1445" alt="Screen Shot 2023-09-02 at 15 10 25" src="https://github.com/zhipuai/zhipuai-sdk-python/assets/35788274/f557d2a4-0040-4fde-a965-26baafaabf31">

**Comment by danyang-rainbow** [comment]
重复惩罚调高一些

**Comment by zapp926** [comment]
好的，我试下，谢谢
