### ISSUE TITLE
关于模型`prompt`参数列表长度为奇数的疑问。

### ISSUE THREAD

**Issue by etveritas** [zhipuai/zhipuai-sdk-python#6]
请问，如下图所示，`prompt`参数数据结构要求为列表，在调用接口实验过程中，发现该列表参数必须为奇数，请问这样的设计的考虑是什么。
<img width="986" alt="image" src="https://github.com/zhipuai/zhipuai-sdk-python/assets/27916175/52adfd16-862e-4df4-bf31-15c4dd710749">

**Comment by thincal** [comment]
这里的prompt设计为历史QA对+本次的问，所以为奇数。

**Comment by etveritas** [comment]
好的，谢谢

**Comment by FunnySaltyFish** [comment]
> 这里的prompt设计为历史QA对+本次的问，所以为奇数。

能否将这个限制去掉？事实上，在实际应用中，用户消息的截断可能是用户侧已经做了（截出来的对话50%概率不是奇数），而且由于种种情况不会保持一问一答的形式（断网或者敏感信息重试时，可能连续两个 user），或者用两个 user ，第一个用于指定系统 Prompt（因为你这里没有 system 的 role）、第二个才是真实用户的发送。

另外，你们现在的 API 返回的错误消息很有迷惑性，当对话列表为偶数时，返回的报错是：
> [1214][history参数非法。请检查文档。]

而这个参数叫 `prompt`。这让我花了非常长的时间来找哪里出现了 history 参数，也建议改掉。
